### ISSUE TITLE
Report to increase parameters by "-G", but don't know how.

### ISSUE THREAD

**Issue by ny-shao** [grigoriev-lab/GROM#4]
I am trying GROM, but got warning: "WARNING: Breakpoint array for chromosome is full. Use -G to increase array size.".
I checked the source, and it looks like related to g_sv_list_len_over. But I could not find the option to set G parameter. Is it ok to use the result with the warning?

**Comment by sdsdusty** [comment]
The results may be missing some variant predictions at the end of chromosomes.  The default setting for -G is 1000000.  Try doubling this parameter by adding -G 2000000 to the command line.  If this does not remove the warning, set -G to a higher value.  

Thank you for your interest in GROM and noting the absence of -G in the documentation.  I'll add it to the README and GROM help.

Sean

**Comment by ny-shao** [comment]
Thank you, Sean! I will follow your suggestion.
